version: '3'
services:
    shoppingcart-app:
        image: lab4.southeastasia.cloudapp.azure.com/shoppingcart
        deploy:
            replicas: 6
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://35.168.203.14:3306/shopping_cart_db?useUnicode=true&characterEncoding=utf8&useSSL=false
            - APP_SLEEP=50 # gives time for the database to boot before the application
        ports:
            - 80:8070
    shoppingcart-mysql:
        image: mysql:5.7.18
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=shopping_cart_db
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
        deploy:
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - 9001:8080
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
